'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SaherBlueEagle_RanRAT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bluexform() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bluexform", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bluexform1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bluexform1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''Afghanistan|33.00,65.00
        '''
        '''Akrotiri|34.37,32.58
        '''
        '''Albania|41.00,20.00
        '''
        '''Algeria|28.00,3.00
        '''
        '''American Samoa|-14.20,-170.00
        '''
        '''Andorra|42.30,1.30
        '''
        '''Angola|-12.30,18.30
        '''
        '''Anguilla|18.15,-63.10
        '''
        '''Antarctica|-90.00,0.00
        '''
        '''Antigua and Barbuda|17.03,-61.48
        '''
        '''Arctic Ocean|90.00,0.00
        '''
        '''Argentina|-34.00,-64.00
        '''
        '''Armenia|40.00,45.00
        '''
        '''Aruba|12.30,-69.58
        '''
        '''Ashmore and Cartier Islands|-12.14,123.05
        '''
        '''Atlantic Ocean|0.00,-25.00
        '''
        '''Australia|-27.00,133.00
        '''
        '''Austria|47.20,13.20
        '''
        '''Azerbaijan|40.30,47.30        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property countryinfo() As String
            Get
                Return ResourceManager.GetString("countryinfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property dangernogui() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dangernogui", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property nRansomwarex() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("nRansomwarex", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property nRansomwarexEditor() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("nRansomwarexEditor", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property project() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("project", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property reac() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("reac", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redxform() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redxform", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property redxform1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("redxform1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Saher_Blue_Eagle_Ransomware() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Saher_Blue_Eagle_Ransomware", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shell1() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shell1", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shell2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shell2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shell3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shell3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shell4() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shell4", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shell5() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shell5", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shell6() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shell6", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shell7() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shell7", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property svchdec() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("svchdec", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System.Net.Sockets
        '''Imports System.Collections.Generic
        '''Imports System.Drawing
        '''Imports Microsoft.VisualBasic.Strings
        '''Imports System.Windows.Forms
        '''Imports System.Drawing.Imaging
        '''Imports System.Drawing.Drawing2D
        '''Imports System.Runtime.InteropServices
        '''Imports System, Microsoft.VisualBasic
        '''Imports System.Diagnostics
        '''Imports System.IO
        '''Imports System.Threading
        '''Imports Microsoft.VisualBasic.Constants
        '''Imports Microsoft.VisualBasic.Interaction
        '''Imports Microsoft.VisualBasic.Conversion
        '''Imports Mic [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property svchdec1() As String
            Get
                Return ResourceManager.GetString("svchdec1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property themexdesign() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("themexdesign", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property themexdesign1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("themexdesign1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property xxx() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("xxx", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
